apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.database.headlessServiceName }}
    namespace: {{ .Values.namespace }}
    labels:
        app: {{ .Release.Name }}-postgres
spec:
    clusterIP: None
    selector:
        app: {{ .Release.Name }}-postgres
    ports:
        - port: 5432
