apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.secretName }}
    namespace: {{ .Values.namespace }}
type: Opaque
data:
    DB_URL: {{ .Values.secrets.DB_URL | quote }}
    JWT_SECRET: {{ .Values.secrets.JWT_SECRET | quote }}
    PORT: {{ .Values.secrets.PORT | quote }}
    POSTGRES_USER: {{ .Values.secrets.POSTGRES_USER | quote }}
    POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD | quote }}
    DB: {{ .Values.secrets.DB | quote }}
