apiVersion: apps/v1
kind: Deployment
metadata:
    name: secureguard-api
    namespace: secureguard
spec:
    replicas: 1
    selector:
        matchLabels:
            app: secureguard-api
    template:
        metadata:
            labels:
                app: secureguard-api
        spec:
            initContainers:
                - name: create-database
                  image: postgres:15
                  command: ["/bin/sh", "-c", 'psql "$DB_URL" -c "CREATE DATABASE secureguard;"']
                  env:
                      - name: DB_URL
                        valueFrom:
                            secretKeyRef:
                                name: db-credentials
                                key: DB_URL
                - name: run-migrations
                  image: postgres:15
                  command:
                      - /bin/sh
                      - -c
                      - |
                          echo "Running migrations..."
                          psql "$DB_URL" -f /migrations/001_init.up.sql
                  env:
                      - name: DB_URL
                        valueFrom:
                            secretKeyRef:
                                name: db-credentials
                                key: DB_URL
                  volumeMounts:
                      - name: migration-scripts
                        mountPath: /migrations
            containers:
                - name: secureguard-api
                  image: akshayyyyy/secureguard-api
                  ports:
                      - containerPort: 4000
                  env:
                      - name: JWT_SECRET
                        valueFrom:
                            secretKeyRef:
                                name: db-credentials
                                key: JWT_SECRET
                      - name: PORT
                        valueFrom:
                            secretKeyRef:
                                name: db-credentials
                                key: PORT
                      - name: DB_URL
                        valueFrom:
                            secretKeyRef:
                                name: db-credentials
                                key: DB_URL
            volumes:
                - name: migration-scripts
                  configMap:
                      name: db-migrations