apiVersion: v1
kind: Secret
metadata:
    creationTimestamp: null
    name: db-credentials
data:
    DB_URL: "cG9zdGdyZXM6Ly9teXVzZXI6bXlwYXNzd29yZEBwb3N0Z3Jlcy1obDo1NDMyL3Bvc3RncmVzP3NzbG1vZGU9ZGlzYWJsZQ=="
    JWT_SECRET: "NDRIQU1JTFRPTldBU0hFRA=="
    PORT: "NDAwMA=="
    POSTGRES_USER: "bXl1c2Vy"
    POSTGRES_PASSWORD: "bXlwYXNzd29yZA=="
    DB: "c2VjdXJlZ3VhcmQ="